# Global build settings
[build]
  # Root directory where package.json and source code live
  base = "."
  
  # Directory containing deploy-ready assets (usually .next folder for Next.js)
  publish = "cupid-ui/.next"

  # Default build command, assuming you're using npm for the build process
  command = "npm run build"

  # Node.js environment version for consistency across all environments
  [build.environment]
  NODE_VERSION = "16.15.0"
  RUBY_VERSION = "2.7.2" # Ruby version if needed (typically not needed for Next.js)

# Serverless function settings (if applicable)
[functions]
  directory = "cupid-ui/netlify/functions"  # Path for serverless functions

# Redirects and headers (Add more specific redirects as needed)
[[redirects]]
  from = "/*"
  to = "/index.html"   # Default redirect if no specific route matches
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "frame-ancestors https://www.facebook.com"

# Context-specific settings for different environments (Production and Deploy Preview)
[context.production]
  publish = "cupid-ui/.next"  # Ensure `.next` is used for production build
  command = "npm run build"  # Use 'npm run build' instead of any other build commands

  [context.production.environment]
  NODE_VERSION = "16.15.0"  # Ensure Node.js version compatibility

[context.deploy-preview]
  publish = "cupid-ui/.next"  # Same for preview deployments
  command = "npm run build"  # Use 'npm run build' for preview

  [context.deploy-preview.environment]
  NOT_PRIVATE_ITEM = "not so secret"  # Set any environment variables needed for deploy preview

# Local development overrides (using Netlify Dev)
[dev]
  command = "npm run dev"  # Start local development server
  port = 8888
  publish = "cupid-ui/.next"  # Ensure `.next` is used for local dev build output

# Plugins for performance monitoring or other integrations
[[plugins]]
  package = "@netlify/plugin-lighthouse"  # Optional plugin for Lighthouse performance audits
